server:
  port: 3510
  servlet:
    context-path: /api/v1.0


spring:
  application:
    name: CLEAR-BG-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/clearbg
    username: postgres
    password: Eshwar@351
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect









